### ISSUE TITLE
why is theia looking for a package.json ?

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri-theia#3]
```
./theia-x86_64-apple-darwin 
root ERROR Failed to start the backend application.
root ERROR Error: ENOENT: no such file or directory, open '/[redacted]/tauri-theia/src-tauri/target/release/bundle/osx/app.app/Contents/MacOS/package.json'
```

`echo '{}' > package.json` got it to start

**Comment by nklayman** [comment]
Had to make an update to `@theia/application-package/src/application-package.ts`, line 98. It would try to read a `package.json` file from the root dir. I added a check to make sure the file exists before reading:
```js
return this._pck = existsSync(this.packagePath) ? readJsonFile(this.packagePath) : {};
```

I packed the custom version and it is now used in the tauri-theia repo, fixing the issue.
